Extension { #name : #Object }

{ #category : #'*MudTalk-Parsers' }
Object >> isTelnetCommand [
	^ false
]

{ #category : #'*MudTalk-Parsers' }
Object >> isTelnetDo [
	^ false
]

{ #category : #'*MudTalk-Parsers' }
Object >> isTelnetDont [
	^ false
]

{ #category : #'*MudTalk-Parsers' }
Object >> isTelnetSubnego [
	^ false
]

{ #category : #'*MudTalk-Parsers' }
Object >> isTelnetWill [
	^ false
]

{ #category : #'*MudTalk-Parsers' }
Object >> isTelnetWont [
	^ false
]
